# Generated by Django 4.0.10 on 2023-07-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('Male', 'Men'), ('Female', 'Women'), ('Unisex', 'Unisex')], default='U', max_length=20),
        ),
    ]
